name: plataforma
description: Hacka Token Sport NFT App

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: 1.1.0  # ✅ Versão atualizada
  provider: ^6.0.5
  url_launcher: ^6.1.10
  js: ^0.6.7
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
